service: resize-images-otf

useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  policy_version: "2012-10-17"
  stage: ${opt:stage, self:provider.stage}
  settings:
    dev:
      S3_BUCKET: ace1-sneakers-images-test
    prod:
      S3_BUCKET: sneakers-cdn.ace1.com.br

provider:
  name: aws
  runtime: nodejs14.x

  # Default memory size for functions (default: 1024MB)
  memorySize: 1024

  # Default timeout for functions (default: 6 seconds)
  # Note: API Gateway has a maximum timeout of 30 seconds
  timeout: 10

  # Function environment variables
  environment:
    S3_BUCKET: ${self:custom.settings.${self:custom.stage}.S3_BUCKET}

  # Duration for CloudWatch log retention (default: forever)
  logRetentionInDays: 30

  # Version of hashing algorithm used by Serverless Framework for function packaging
  lambdaHashingVersion: 20201221

  # Processor architecture: 'x86_64' or 'arm64' via Graviton2 (default: x86_64)
  # architecture: x86_64

  # Default region (default: us-east-1)
  region: us-west-2

  # Default stage (default: dev)
  stage: dev

functions:
  createTradesmanFunc:
    handler: src/handler.handler
    events:
      - http:
          path: /hello-world
          method: get

resources:
  Resources:
    S3Bucket:
      Type: "AWS::S3::Bucket"
      Properties:
        AccessControl: public-read
        BucketName: ${self:custom.settings.${self:custom.stage}.S3_BUCKET}
        WebsiteConfiguration:
          IndexDocument: index.html
          # ErrorDocument: error.html # (Optional)
          RoutingRules:
            - RoutingRuleCondition:
                HttpErrorCodeReturnedEquals: "404"
              RedirectRule:
                HttpRedirectCode: "307"
                Protocol: https
                # TODO: pegar a url de API Gateway quando for gerada
                HostName: jhrjy88z83.execute-api.us-east-1.amazonaws.com
                # TODO: pegar modo PROD e DEV
                ReplaceKeyPrefixWith: default/${self:service}?path=
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - "*" # TODO: definir quais endpoints
              AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - PUT
                - HEAD
              MaxAge: 84600

    ApplicationRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ApplicationRole # required if you want to use 'serverless deploy --function' later on
        AssumeRolePolicyDocument:
          Version: ${self:custom.policy_version}
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole

        # Pattern: Service-Name:(Allow|Deny):Action-Type
        Policies:
          - PolicyName: "S3:Allow:PutObject"
            PolicyDocument:
              Version: ${self:custom.policy_version}
              Statement:
                - Effect: "Allow"
                  Action:
                    - "s3:PutObject"
                  Resource: !Join
                      - ""
                      - - "arn:aws:s3:::"
                        - !Ref "ServerlessDeploymentBucket"

          - PolicyName: "CloudWatch:Allow:CreateLogs"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow # note that these rights are given in the default policy and are required if you want logs out of your lambda(s)
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - !Join
                      - ":"
                      - - "arn:aws:logs"
                        - !Ref "AWS::Region"
                        - !Ref "AWS::AccountId"
                        - "log-group:/aws/lambda/*:*:*"

  Outputs:
    WebsiteURL:
      Value: !GetAtt
        - S3Bucket
        - WebsiteURL
      Description: URL for website hosted on S3
    S3BucketSecureURL:
      Value: !Join
        - ""
        - - "https://"
          - !GetAtt
            - S3Bucket
            - DomainName
      Description: Name of S3 bucket to hold website content
